// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpvbrycuuumagwstxcjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwdmJyeWN1dXVtYWd3c3R4Y2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NDQ5MjAsImV4cCI6MjA2NzAyMDkyMH0.nl6lzCcZuT2F-AN_L_XtUUKhMycWrqJoA7DwsdxR9Vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});